trigger:
- manual

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: Veracode Container CLI
  inputs:
    script: |
      pwd
      echo "Export credentials from Azure variables"
      export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
      echo "Installing Veracode CLI"
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      echo "Pull credentials from the exported credentials above"
      ./veracode configure
      echo "Scan containers alpine:latest and bitnami/moodle"
      ./veracode scan --source /home/vsts/work/1/s/ --type directory --format json --output ./veracode_container_scan.json
      
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'veracode_container_scan.json'
    pathToPublish: '$(System.DefaultWorkingDirectory)/veracode_container_scan.json'
  displayName: 'Publish veracode_container_scan.json Artifact'
