name: Veracode Pipeline Scan
on: workflow_dispatch
    
jobs:
  pipeline_scan:
    name: Pipeline Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Build with Maven
        run: mvn -B package --file app/pom.xml
          
      # - name: Pipeline Scan
      #   run: |
      #     curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      #     unzip -o pipeline-scan-LATEST.zip
      #     java -jar pipeline-scan.jar -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }} --json_output_file="results.json" -f app/target/verademo.war || true
      #   continue-on-error: true
      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.3
          #julz0815/Veracode-pipeline-scan-action@beta-0.29
        with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            file: "verademo.war" 
            request_policy: "OWASP 10"
            store_baseline_file: true
            store_baseline_file_branch: "Feature-123"
            create_baseline_from: "standard"
            debug: 1
            fail_build: false

      - name: Upload results.json
        uses: actions/upload-artifact@v2
        with:
          name: Scan Results
          path: /home/runner/work/verademo/verademo/results.json
