name: Veracode Static Analysis
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
    
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Build with Maven
        run: mvn -B package --file app/pom.xml
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
          appname: 'Verademo'
          createprofile: false
          sandboxname: 'GitHub'
          createsandbox: false
          filepath: 'app/target/verademo.war'
          # scan name
          version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          scantimeout: 60
          deleteincompletescan: 2
#         debug: true
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'
